openapi: 3.0.0
info:
  title: Computer components API
  version: 1.0.0
servers:
  - url: /api
paths:
  /exhibitions:
    get:
      summary: List all components
      responses:
        '200':
          description: OK
    post:
      summary: Create a new component
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Computer'
      responses:
        '201':
          description: Created
  /exhibitions/{id}:
    put:
      summary: Update a component
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: The component identifier
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Computer'
      responses:
        '200':
          description: OK
        '404':
          description: Components not found
    delete:
      summary: Delete an exhibition
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: The components identifier
      responses:
        '204':
          description: No Content
        '404':
          description: Component not found
components:
  schemas:
    Exhibition:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        date:
          type: string
        location:
          type: string
        participants:
          type: integer
      required:
        - name
        - catergory
        - price


