openapi: 3.0.0
info:
  title: Exhibition API
  version: 1.0.0
servers:
  - url: /api
paths:
  /exhibitions:
    get:
      summary: List all exhibitions
      responses:
        '200':
          description: OK
    post:
      summary: Create a new exhibition
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Exhibition'
      responses:
        '201':
          description: Created
  /exhibitions/{id}:
    put:
      summary: Update an exhibition
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: The exhibition identifier
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Exhibition'
      responses:
        '200':
          description: OK
        '404':
          description: Exhibition not found
    delete:
      summary: Delete an exhibition
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: The exhibition identifier
      responses:
        '204':
          description: No Content
        '404':
          description: Exhibition not found
components:
  schemas:
    Exhibition:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        date:
          type: string
        location:
          type: string
        participants:
          type: integer
      required:
        - name
        - date
        - location
        - participants
